enum ProductCategory {
  appliances,
  artSupplies,
  automotive,
  beauty,
  books,
  clothing,
  construction,
  drink,
  electronics,
  food,
  furniture,
  gardening,
  health,
  home,
  jewelry,
  musicalInstruments,
  officeSupplies,
  other,
  pets,
  sports,
  toys,
}

final Map<ProductCategory, String> productCategoryTranslations = {
  ProductCategory.appliances: 'Eletrodomésticos',
  ProductCategory.artSupplies: 'Materiais de Arte',
  ProductCategory.automotive: 'Automotivo',
  ProductCategory.beauty: 'Cosméticos',
  ProductCategory.books: 'Livros',
  ProductCategory.clothing: 'Vestuário',
  ProductCategory.construction: 'Construção',
  ProductCategory.drink: 'Bebida',
  ProductCategory.electronics: 'Eletrônicos',
  ProductCategory.food: 'Alimentos',
  ProductCategory.furniture: 'Móveis',
  ProductCategory.gardening: 'Jardinagem',
  ProductCategory.health: 'Saúde',
  ProductCategory.home: 'Casa',
  ProductCategory.jewelry: 'Jóias',
  ProductCategory.musicalInstruments: 'Instrumentos Musicais',
  ProductCategory.officeSupplies: 'Material de Escritório',
  ProductCategory.other: 'Outros',
  ProductCategory.pets: 'Animais de Estimação',
  ProductCategory.sports: 'Esportes',
  ProductCategory.toys: 'Brinquedos',
};
