// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARVUw4VqY_A6gESvMIKnrFzafTKp1KxyU',
    appId: '1:553185583606:web:6b4a9fb989202ab9d067d7',
    messagingSenderId: '553185583606',
    projectId: 'marba-project',
    authDomain: 'marba-project.firebaseapp.com',
    storageBucket: 'marba-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0h3XsRSompqLMUqdY07wRpfAPZSSDtI',
    appId: '1:553185583606:android:999464fc46ac29fbd067d7',
    messagingSenderId: '553185583606',
    projectId: 'marba-project',
    storageBucket: 'marba-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnpQnodWvvjrjGfkNqdVGefYv_lVCpZ0Y',
    appId: '1:553185583606:ios:a78675b18bc6e8abd067d7',
    messagingSenderId: '553185583606',
    projectId: 'marba-project',
    storageBucket: 'marba-project.appspot.com',
    iosBundleId: 'com.example.projectMarba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnpQnodWvvjrjGfkNqdVGefYv_lVCpZ0Y',
    appId: '1:553185583606:ios:e30afcc2dd3ed5f7d067d7',
    messagingSenderId: '553185583606',
    projectId: 'marba-project',
    storageBucket: 'marba-project.appspot.com',
    iosBundleId: 'com.example.projectMarba.RunnerTests',
  );
}
